require("dotenv").config();
const nodemailer = require("nodemailer");
const transport = nodemailer.createTransport({
  service: "Gmail",
  auth: {
    user: process.env.email,
    pass: process.env.password,
  },
});
const sendEmail = (to, subject, message) => {
  const mailOptions = {
    from: "test6204861229@gmail.com",
    to,
    subject,
    html: message,
  };
  transport.sendMail(mailOptions, (error) => {
    if (error) {
      console.log(error);
    } else {
      console.log("success");
    }
  });
};

const generateMessage = (id, name) => {
  const message = `Hello ${name},
              <br/><br/>
              ${name} your <strong>VB ERP</strong> account has created please click on below link to generate your Password
              <br/><br/>
              <small><a href="${process.env.ORIGIN}/${id}/setpassword">${process.env.ORIGIN}/${id}/setpassword</a></small><br/><br/>
              <small>This email is auto-generated by <strong>VB-ERP</strong></small>.<br/>
              <small><i>Please do not reply to this message</i></small><br/><br/><br/>`;
  return message;
};
module.exports = { sendEmail, generateMessage };
